services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: user
      POSTGRES_DB: local
    volumes:
      - nest_docker_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: secretpassword
      DB_DATABASE: local
    ports:
      - '3000:3000'

volumes:
  nest_docker_postgres_data:
