FROM node:20 AS base

WORKDIR /app

COPY package*.json ./

COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

# Bundle app source
COPY src .

COPY db ./db/

COPY tsconfig*.json ./

COPY entrypoint.sh ./

RUN pnpm build

EXPOSE 3000

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["pnpm", "start"]
